# Run PHP Code Sniffer (PHPCS) and comment on the pull request with any issues.
#
# This file is managed in https://github.com/happyprime/projects
name: PHPCS (PHP 8.2)

on: pull_request

# The GITHUB_TOKEN used by Dependabot has read-only permissions by default. We
# provide write permissions to this workflow so that comments can be left on
# the pull request.
#
# @see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  call-workflow:
    uses: happyprime/workflows/.github/workflows/phpcs.yml@trunk
    with:
      php-version: '8.2'
