# This file is managed in https://github.com/happyprime/projects
name: Verify build (Node 20)

on: pull_request

# The GITHUB_TOKEN used by Dependabot has read-only permissions by default. We
# provide write permissions to this workflow so that comments can be left on
# the pull request.
#
# @see https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#changing-github_token-permissions
permissions:
  contents: read
  pull-requests: write

jobs:
  call-workflow:
    uses: happyprime/workflows/.github/workflows/verify-build.yml@trunk
    with:
      node-version: 20
